### ISSUE TITLE
panic error on jobs:97

### ISSUE THREAD

**Issue by korjavin** [drbig/grabber#1]
```
[{  
  "name": "Menzel NOUR",
  "url": "http://www.booking.com/hotel/tn/menzel-nour.html",
  "bail": 10, 
  "path": "./",
  "do": {
    "command": "print",
    "action": {
      "mode": "every", "type": "xpath",
      "args": ["//*[@id='hp_hotel_name']"]
    }   
  }         
}]  
```

```
2016/11/30 22:13:02 Target: Menzel NOUR
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 11 [running]:
panic(0x55b6b368b5c0, 0xc420112170)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/moovweb/gokogiri/xml._cgoCheckPointer0(0xc4201142a0, 0x0, 0x0, 0x0, 0x2004dc58)
	??:0 +0x59
github.com/moovweb/gokogiri/xml.(*XmlNode).serialize(0xc42010c260, 0x41, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42010c240, 0x55b6b368be20, ...)
	/home//Projects/go/src/github.com/moovweb/gokogiri/xml/node.go:773 +0x10c
github.com/moovweb/gokogiri/xml.(*XmlNode).ToHtml(0xc42010c260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42010c240, 0xc42004dd58, 0x55b6b3429705, ...)
	/home//Projects/go/src/github.com/moovweb/gokogiri/xml/node.go:826 +0x83
github.com/moovweb/gokogiri/xml.(*XmlNode).ToBuffer(0xc42010c260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home//Projects/go/src/github.com/moovweb/gokogiri/xml/node.go:833 +0x91
github.com/moovweb/gokogiri/xml.(*XmlNode).String(0xc42010c260, 0x0, 0x0)
	/home//Projects/go/src/github.com/moovweb/gokogiri/xml/node.go:841 +0x4a
main.(*Job).doXPath(0xc4200bea20, 0x55b6b3a57a50, 0x0, 0x0, 0x0, 0x0)
	/home//Projects/go/src/github.com/drbig/grabber/jobs.go:97 +0x2fe
main.parser()
	/home//Projects/go/src/github.com/drbig/grabber/workers.go:45 +0xb38
created by main.main
	/home//Projects/go/src/github.com/drbig/grabber/main.go:89 +0x586
```

**Comment by drbig** [comment]
Wow.

```
panic(0x55b6b368b5c0, 0xc420112170)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/moovweb/gokogiri/xml._cgoCheckPointer0(0xc4201142a0, 0x0, 0x0, 0x0, 0x2004dc58)
	??:0 +0x59
```

Looks like a `gokogiri` problem? And given it does CGO - or (assuming here) your `libxml` problem?
Doesn't seem like anything that needs fixing on the `grabber` level.
